apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: springboot-svc
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80    
  selector:
    run: springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: springboot
  name: springboot-ds
spec:
  replicas: 1
  selector:
    matchLabels:
      run: springboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: springboot
    spec:
      containers:
      - image: amikshas/a-gs-spring-boot-docker:2021-24_1
        name: springboot
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
status: {}

