kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
          name: role-user1
          namespace: <namespace_name>
subjects:
       - kind: User
         name: user1
         apiGroup: ""
roleRef:
         kind: Role
         name: user1-role
         apiGroup: ""
