---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: sudo docker build -t springboot-image:latest .
    args:
      chdir: ~/k8s-lab

  - name: create tag to image
    command: sudo docker tag springboot-image amikshas/springboot-image

  - name: push image on to dockerhub
    command: sudo docker push amikshas/springboot-image

  - name: remove docker images form ansible server
    command: sudo docker rmi amikshas/springboot-image springboot-image:latest
    ignore_errors: yes
