---
- name: Create pods using deployment 
  hosts: kubemaster 
  # become: true
  user: ubuntu
 
  tasks: 
  - name: create a deployment
    command: sudo kubectl apply -f ~/k8s-lab/kube-deploy-springboot-app.yml
 
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/springboot-ds
