---
- name: create service for deployment
  hosts: kubemaster
  # become: true
  user: ubuntu

  tasks:
  - name: create a service
    command: kubectl apply -f ~/k8s-lab/kube-deploy-springboot-svc.yml
