apiVersion: apps/v1 
kind: Deployment
metadata:
  name: springboot-ds
  labels:
    app: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: amikshas/a-gs-spring-boot-docker:2021-27_1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
status: {}
