apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  labels:
    app: springboot
spec:
  selector:
    app: springboot
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
